### ISSUE TITLE
pacbot-admin and pacbot-auth ECS tasks are stopped abruptly

### ISSUE THREAD

**Issue by sonawanesangram** [tmobile/pacbot#121]
## Micro services
- Spring boot Applications:
 -  Admin Service
 - Auth Service
 
- OS Type: Linux
- Java version:
 - 1.8

## Summary
After installing pacbot 1.1 we have seen ECS tasks for pacbot-auth: and pacbot-admin are stopped abruptly when trying to create/update federated rules, create/update Target type, Invoke rule.

The error is not consistent and we can see this 70% of the time, sometimes its works fine.
Additional change we did in pacbot setup was to enable HTTPS and ALB is public facing.

## Reproduce steps
- Login to pacbot and try to create a new federated rule.
- Login to pacbot and try to create a new target type.
- Login to pacbot and try to invoke an rule 

## Expected Results
- Federated, Target type should be created.
- Rule should be invoked. 

## Actual Results
pacbot-admin and pacbot-auth ECS tasks are stopped. Error details below:
c.t.p.api.admin.AdminApplication.logStarted - Started AdminApplication in 47.85 seconds (JVM running for 49.239)
18-02-2019 07:09:35.134 [http-nio-80-exec-1] INFO
o.a.c.c.C.[.[localhost].[/api/admin].log - Initializing Spring FrameworkServlet 'dispatcherServlet'
18-02-2019 07:09:35.135 [http-nio-80-exec-1] INFO
o.s.web.servlet.DispatcherServlet.initServletBean - FrameworkServlet 'dispatcherServlet': initialization started
18-02-2019 07:09:35.200 [http-nio-80-exec-1] INFO
o.s.web.servlet.DispatcherServlet.initServletBean - FrameworkServlet 'dispatcherServlet': initialization completed in 65 ms
18-02-2019 07:09:35.476 [http-nio-80-exec-1] INFO
c.t.p.a.a.config.CrossOriginFilter.doFilter - Applying CORS filter
/root/pacman-api-admin.jar: line 260: 40 Killed "$javaexe" "${arguments[@]}"

**Comment by sonawanesangram** [comment]
**Complete Cloud Watch Logs:**

s.d.s.w.s.ApiListingReferenceScanner.scan - Scanning for api listing references
26-02-2019 02:40:13.011 [main] INFO
s.d.s.w.r.o.CachingOperationNameGenerator.startingWith - Generating unique operation named: createAssetGroupDetailsUsingPOST_1
26-02-2019 02:40:13.032 [main] INFO
s.d.s.w.r.o.CachingOperationNameGenerator.startingWith - Generating unique operation named: createAssetGroupDetailsUsingPOST_2
26-02-2019 02:40:13.411 [main] INFO
s.d.s.w.r.o.CachingOperationNameGenerator.startingWith - Generating unique operation named: getRulesByIdUsingGET_1
26-02-2019 02:40:13.554 [main] INFO
s.d.s.w.r.o.CachingOperationNameGenerator.startingWith - Generating unique operation named: getRulesByIdUsingGET_2
26-02-2019 02:40:14.234 [main] INFO
c.t.p.a.a.r.s.EsIndexInitializerServiceImpl.lambda$executeEsIndexInitializer$0 - triggering executeExceptionIndexInitializer
26-02-2019 02:40:14.489 [main] INFO
c.t.p.a.a.r.s.EsIndexInitializerServiceImpl.lambda$executeEsIndexInitializer$0 - triggering executeExceptionIndexInitializer
26-02-2019 02:40:14.523 [main] ERROR
c.t.p.api.commons.utils.PacHttpUtils.doHttpPut -
{
    "index": {
        "_index": "faqs",
        "_type": "widgetinfo",
        "_id": "w1"
    }
}

{
    "widgetid": "w1",
    "widgetname": "compliance overview"
}

{
    "index": {
        "_index": "faqs",
        "_type": "widgetinfo",
        "_id": "w2"
    }
}

{
    "widgetid": "w2",
    "widgetname": "patching"
}

{
    "index": {
        "_index": "faqs",
        "_type": "widgetinfo",
        "_id": "w3"
    }
}

{
    "widgetid": "w3",
    "widgetname": "tagging"
}

{
    "index": {
        "_index": "faqs",
        "_type": "widgetinfo",
        "_id": "w4"
    }
}

{
    "widgetid": "w4",
    "widgetname": "vulnerabilities"
}

{
    "index": {
        "_index": "faqs",
        "_type": "widgetinfo",
        "_id": "w5"
    }
}

{
    "widgetid": "w5",
    "widgetname": "certificates"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w2q7"
    }
}

{
    "faqid": "q7",
    "faqname": "How is unpatched count calculated ?",
    "answer": "Total assets which does not have updated kernel version.",
    "widgetid": "w2",
    "tag": "patching"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w3q4"
    }
}

{
    "faqid": "q4",
    "faqname": "How is tagging compliance % calculated ?",
    "answer": "Tagging compliance is calculated by dividing total taggable assets by total tagged assets.",
    "widgetid": "w3",
    "tag": "tagging"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w1q1"
    }
}

{
    "faqid": "q1",
    "faqname": "What is shown in this graph?",
    "answer": "This multi ring donut represents the overall compliance percentage. Policies are grouped into categories like security, governance, cost optimization and tagging. Rings in the donut represents compliance percentage for each of those categories.  The rolled up percentage value for a given category is calculated by doing a weighted average of compliance percentage values of individual policies in that category. Weights are assigned based on the importance of the policy. Overall rolled up number in the middle of the donut represents uber compliance percentage for the selected asset group. This value is calculated by doing a simple average of compliance percentage values of the four categories.",
    "widgetid": "w1",
    "tag": "over-all"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w4q5"
    }
}

{
    "faqid": "q5",
    "faqname": "How is vulnerabilities compliance % calculated ?",
    "answer": "Vulnerabilities compliance is calculated by dividing total vulnerable assets by total servers, if an asset is not scanned by qualys , then the asset is considered as vulnerable.",
    "widgetid": "w4",
    "tag": "vulnerabilities"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w5q3"
    }
}

{
    "faqid": "q3",
    "faqname": "How is certificates compliance % calculated ?",
    "answer": "Total non-expired certificates divided by total certificates",
    "widgetid": "w5",
    "tag": "certificates"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w3q8"
    }
}

{
    "faqid": "q8",
    "faqname": "How is untagged count calculated ?",
    "answer": "Total assets which is missing either application/environment tags or both tags.",
    "widgetid": "w3",
    "tag": "tagging"
}

{
    "index": {
        "_index": "faqs",
        "_type": "faqinfo",
        "_id": "w2q2"
    }
}

{
    "faqid": "q2",
    "faqname": "How is patching compliance % calculated ?",
    "answer": "Total patched resources divided by total running resources",
    "widgetid": "w2",
    "tag": "patching"
}
26-02-2019 02:40:14.524 [main] ERROR
c.t.p.api.commons.utils.PacHttpUtils.doHttpPut - error closing issueunable to execute post request because Bad Request
26-02-2019 02:40:14.525 [main] INFO
c.t.p.a.a.r.s.EsIndexInitializerServiceImpl.lambda$executeEsIndexInitializer$0 - Exception in executeExceptionIndexInitializer: unable to execute post request because Bad Request
java.lang.Exception: unable to execute post request because Bad Request
at com.tmobile.pacman.api.commons.utils.PacHttpUtils.doHttpPut(PacHttpUtils.java:243)
at com.tmobile.pacman.api.admin.repository.service.EsIndexInitializerServiceImpl.lambda$executeEsIndexInitializer$0(EsIndexInitializerServiceImpl.java:80)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at com.tmobile.pacman.api.admin.repository.service.EsIndexInitializerServiceImpl.executeEsIndexInitializer(EsIndexInitializerServiceImpl.java:61)
at com.tmobile.pacman.api.admin.EsIndexInitializer.onApplicationEvent(EsIndexInitializer.java:18)
at com.tmobile.pacman.api.admin.EsIndexInitializer.onApplicationEvent(EsIndexInitializer.java:10)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
at com.tmobile.pacman.api.admin.AdminApplication.main(AdminApplication.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
26-02-2019 02:40:14.547 [main] INFO
o.a.coyote.http11.Http11NioProtocol.log - Starting ProtocolHandler ["http-nio-80"]
26-02-2019 02:40:14.558 [main] INFO
o.a.tomcat.util.net.NioSelectorPool.log - Using a shared selector for servlet write/read
26-02-2019 02:40:14.592 [main] INFO
o.s.b.w.e.tomcat.TomcatWebServer.start - Tomcat started on port(s): 80 (http) with context path '/api/admin'
26-02-2019 02:40:14.608 [main] INFO
c.t.p.api.admin.AdminApplication.logStarted - Started AdminApplication in 46.642 seconds (JVM running for 48.032)
26-02-2019 02:44:39.829 [http-nio-80-exec-2] INFO
o.a.c.c.C.[.[localhost].[/api/admin].log - Initializing Spring FrameworkServlet 'dispatcherServlet'
26-02-2019 02:44:39.829 [http-nio-80-exec-2] INFO
o.s.web.servlet.DispatcherServlet.initServletBean - FrameworkServlet 'dispatcherServlet': initialization started
26-02-2019 02:44:39.904 [http-nio-80-exec-2] INFO
o.s.web.servlet.DispatcherServlet.initServletBean - FrameworkServlet 'dispatcherServlet': initialization completed in 75 ms
26-02-2019 02:44:40.080 [http-nio-80-exec-2] INFO
c.t.p.a.a.config.CrossOriginFilter.doFilter - Applying CORS filter
26-02-2019 02:44:40.081 [http-nio-80-exec-1] INFO
c.t.p.a.a.config.CrossOriginFilter.doFilter - Applying CORS filter
26-02-2019 05:40:06.873 [http-nio-80-exec-3] WARN
o.s.b.a.s.o.r.UserInfoTokenServices.getMap - Could not fetch user details: class org.springframework.security.oauth2.client.resource.UserRedirectRequiredException, A redirect is required to get the users approval
26-02-2019 05:40:07.552 [http-nio-80-exec-4] INFO
c.t.p.a.a.config.CrossOriginFilter.doFilter - Applying CORS filter
26-02-2019 05:40:19.834 [http-nio-80-exec-1] INFO
c.t.p.a.a.config.CrossOriginFilter.doFilter - Applying CORS filter
26-02-2019 05:40:29.501 [http-nio-80-exec-3] INFO
c.t.p.a.a.config.CrossOriginFilter.doFilter - Applying CORS filter
/root/pacman-api-admin.jar: line 260: 40 Killed "$javaexe" "${arguments[@]}"

**Comment by sonawanesangram** [comment]
We were able to resolve this by increasing the container memory to 2GB. Thanks @sajeer-nooh for the inputs.
