### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by ammar-alim** [tmobile/pacbot#13]
Hello Guys, Seems like a great product thanks for making it available for us.  

I have a few questions for you, hopefully, you have answers for me. 

1- I keep getting this error even though I can see the log file in var/log directory :

$ python setup_pacman.py destroy
Traceback (most recent call last):
  File "setup_pacman.py", line 25, in <module>
    import awsterraformbuild
  File "/home/ec2-user/pacbot/installer/awsterraformbuild.py", line 15, in <module>
    pacman_installation = filecreator.create_pacman_log_file_handler()
  File "/home/ec2-user/pacbot/installer/filecreator.py", line 64, in create_pacman_log_file_handler
    return open(get_logfile_path(), "a+")
IOError: [Errno 13] Permission denied: '/var/log/pacman/pacman-destroy.log'

2- Resources we provisions based on the log file since I got this message: "Apply complete! Resources: 7 added, 0 changed, 0 destroyed." and I can also see the resources in my account but auto-scaling keep terminating the EC2 instances.

3- I can clone the git repo manually but the program keeps erroring about authentication

3- Would stale resources prevent the destroy command from running I only get the error: "System existed"

**Comment by johnakash** [comment]
Hi @ammar-alim ,

Please find our responses below,
1- I keep getting this error even though I can see the log file in var/log directory : 
`Please execute the script using sudo or run the script as root. We are assuming its a permission issue and the above fix will resolve it.`

2- Resources we provisions based on the log file since I got this message: "Apply complete! Resources: 7 added, 0 changed, 0 destroyed." and I can also see the resources in my account but auto-scaling keep terminating the EC2 instances. 
`PacMan have AWS Batch as a component in our architecture, all those EC2 instances are launched for executing batch jobs for processing the data collected. Its an expected behaviour. ` 

3- I can clone the git repo manually but the program keeps erroring about authentication
`While doing the installation, installer used to lookup to the master branch that is why it is showing the error. For now we are suggesting to use key pair to authenticating against the GitHub for installation and will definitely try to remove this dependency in coming release.` 

4- Would stale resources prevent the destroy command from running I only get the error: 
`Yes, it will. Could you please the destroy log (/var/log/pacman/pacman-destroy.log) for getting more details?
`

**Comment by ammar-alim** [comment]
@johnakash -- Thanks for the quick response.

I am I am using a key pain to authenticate against GitHub and I can run git clone just fine but the app sitll througing this error:


Cloning the repository...............

Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/ec2-user/.ssh/pacbot/installer/awsterraformbuild.py", line 27, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/home/ec2-user/.ssh/pacbot/installer/jsonRead.py", line 596, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/home/ec2-user/.ssh/pacbot/installer/ui/build_apps.py", line 35, in build_api_and_ui_apps
    cloned_repo = self.clone_pacman_code()
  File "/home/ec2-user/.ssh/pacbot/installer/ui/build_apps.py", line 89, in clone_pacman_code
    env={'GIT_SSH_COMMAND': "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"}
  File "/usr/lib64/python2.7/site-packages/git/repo/base.py", line 988, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/lib64/python2.7/site-packages/git/repo/base.py", line 939, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/lib64/python2.7/site-packages/git/util.py", line 333, in finalize_process
    proc.wait(**kwargs)
  File "/usr/lib64/python2.7/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v git@github.com:tmobile/pacbot.git /tmp/pacman_cloned_dir_1539378066.06
  stderr: 'Cloning into '/tmp/pacman_cloned_dir_1539378066.06'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by johnakash** [comment]
@ammar-alim  Could you please confirm if you have added the public key to your [github profile](https://github.com/settings/keys)?

If it is there, could you please execute `ssh git@github.com` and see if it is showing as 
```
PTY allocation request failed on channel 0
Hi ammar-alim! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```
As per the log, the machine from which you are executing the script is not able to authenticate against github.

**Comment by ammar-alim** [comment]
Yes, I was able to do so, let me know if you need a screenshot. I cloned it first to run the installer just fine.

**Comment by ammar-alim** [comment]
I am making progress but still fighting the installed, I now get this error:


Creating  batch
pacman file is already created & stored
Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/ec2-user/pacbot/installer/awsterraformbuild.py", line 60, in _create_aws_resources
    region, aws_access_key, aws_secret_key, './container', jsonRead._get_batch_repo(), pacman_installation
  File "/home/ec2-user/pacbot/installer/container/handler.py", line 75, in _create_ecr_image_push
    docker_client = _create_docker_image(dockerfilepath, repository, pacman_installation)
  File "/home/ec2-user/pacbot/installer/container/handler.py", line 54, in _create_docker_image
    for info in docker_client.build(path=dockerfilepath, tag=repository, rm=True, stream=True):
  File "/usr/lib/python2.7/site-packages/docker/api/build.py", line 105, in build
    timeout=timeout,
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 135, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))

**Comment by ammar-alim** [comment]
I was able to resolve this, thanks.

**Comment by badllama** [comment]
@ammar-alim How did you resolve this issue with the 'create_docker_image' step failing with a ConnectionError?
