### ISSUE TITLE
Invalid type for parameter UserName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

### ISSUE THREAD

**Issue by srinathganesh** [tmobile/pacbot#174]
Trying to deploy Pacbot to a AWS instance

1. Subnets are in different AZ

2. Verified key and secret

```
python3 pacbot/installer/manager.py install

###########################################################################################################################
#######################################  ____                                  ____  ######################################
####################################### |/||\|           PacBot               |/||\| ######################################
####################################### . || .   Infra setup and deployment   . || . ######################################
#######################################   ||                                    ||   ######################################
###########################################################################################################################


Step 1: Checking if required tools are availables
	Tool: Maven, checking ................................................................ [Found]
	Tool: Git, checking .................................................................. [Found]
	Tool: MySQL client, checking ......................................................... [Found]
	Tool: Terraform, checking ............................................................ [Found]
	Tool: Nodejs, checking ............................................................... [Found]
	Tool: npm, checking .................................................................. [Found]
	Tool: Angular, checking .............................................................. [Found]
	Tool: Bower, checking ................................................................ [Found]
	Tool: Docker, checking ............................................................... [Found]
	Required tools are available!!!

Step 2: Checking if required python packages are available
	Package: docker, Module: Client, checking ............................................ [Found]
	Module: boto3, checking .............................................................. [Found]
	Required python packages are available!!!

Step 3: Reading required inputs from user
	Required inputs are available!!!

Step 4: Checking settings and inputs
	Checking VPC and CIDR Blocks ......................................................... [Valid]
	Checking VPC subnets ................................................................. [Valid]
	Error occured, please check error log for more details
```

```
Running Command: pacbot/installer/manager.py install
Traceback (most recent call last):
  File "/pacbot/installer/core/kernel.py", line 182, in run
    self.execute(command_class_instance)
  File "/pacbot/installer/core/kernel.py", line 24, in execute
    self.execute_command(command_class_instance)
  File "/pacbot/installer/core/kernel.py", line 36, in execute_command
    command_class_instance.execute(self.provider)
  File "/pacbot/installer/core/commands/install.py", line 39, in execute
    if self.initialize_and_validate():
  File "/pacbot/installer/core/commands/__init__.py", line 115, in initialize_and_validate
    return self.validation_class().validate()
  File "/pacbot/installer/core/providers/aws/validate.py", line 179, in validate
    status = self.validate_user_policies()
  File "/pacbot/installer/core/providers/aws/validate.py", line 99, in validate_user_policies
    if self._check_user_policies(access_key, secret_key, user_name):
  File "/pacbot/installer/core/providers/aws/validate.py", line 140, in _check_user_policies
    user_policy_names = iam.get_iam_user_policy_names(access_key, secret_key, user_name)
  File "/pacbot/installer/core/providers/aws/boto3/iam.py", line 82, in get_iam_user_policy_names
    attached_policies = iam_client.list_attached_user_policies(UserName=user_name)['AttachedPolicies']
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python3.6/dist-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter UserName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Parameter validation failed:
Invalid type for parameter UserName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Error Message: Parameter validation failed:
Invalid type for parameter UserName, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

Upon debugging:

- `iam.CurrentUser().user_id` prints the correct user id
- while `iam.CurrentUser().user_name` returns `None`
- `iam.CurrentUser().arn` prints something like
`'arn:aws:iam::account_id:root'`

IAM permission is to allow everything and instance is bound to IAM

```
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": "iam:*",
        "Resource": "*"
    }
}

```

Found a similar issue at https://github.com/tmobile/pacbot/issues/30 BUT i am using the latest code

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-345

**Comment by sajeer-nooh** [comment]
From the log and error messages what I understood is, you are directly using the credentials generated from the root which do not have a user name.

It would always be recommended to create an IAM user and generate credentials with the permissions required. If you would have used that installation could have completed.
