### ISSUE TITLE
Maven build failed 

### ISSUE THREAD

**Issue by rsathishaws** [tmobile/pacbot#433]
I have installed the pacbot in ubuntu instance but application is not coming up. I'm getting below error 

Maven build started...

Started building the jar...............

Started creating zip file...
Traceback (most recent call last):
  File "/opt/pacbot-master/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 220, in <module>
    s3_key_prefix
  File "/opt/pacbot-master/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 44, in build_api_and_ui_apps
    self.archive_ui_app_build(bucket, s3_key_prefix)
  File "/opt/pacbot-master/installer/data/terraform/scripts_and_files/scripts/build_pacbot.py", line 184, in archive_ui_app_build
    shutil.make_archive(zip_file_name, self.archive_type, dir_to_archive)
  File "/usr/lib/python3.6/shutil.py", line 785, in make_archive
    os.chdir(root_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/pacbot-master/dist/pacmanspa'

**Comment by mboret** [comment]
@rsathishaws I solved this issue with a simple: mkdir /opt/pacbot-master/dist/pacmanspa
And then relaunch the install process.
