### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Gkoh-1** [tmobile/pacbot#498]
I am trying to install the pacbot in aws, It keep on having issues on the docker image not found in the microservice. Please refer to below

## Actual Results

Traceback (most recent call last):
  File "/home/ec2-user/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 80, in <module>
    build_and_push_docker_image(provider_json_file, ecr_repo, docker_file, docker_file_dir, log_file)
  File "/home/ec2-user/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 35, in build_and_push_docker_im
age
    delete_docker_images_from_local(os.path.join(docker_file_dir, docker_file))
  File "/home/ec2-user/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 51, in delete_docker_images_fro
m_local
    docker_client.remove_image(ecr_repo, force=True)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 223, in remove_image
    self._raise_for_status(res)
  File "/usr/local/lib/python3.7/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'{"message":"No such image: 5191x0x08044.dkr.ecr.us-east-1.amazonaws.com/pacbot-microservices:latest"}'
")

**Comment by bestras023** [comment]
Hi, @Gkoh-1 
Did you solve the issue?

**Comment by Gkoh-1** [comment]
No.. I didn't manage to resolve the issue
