### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/ec2-user/pacbot/dist/api/pacman-api-admin.jar'

### ISSUE THREAD

**Issue by chrisswanda** [tmobile/pacbot#62]
Pacbot stops at the below point when doing an install

```
Started building the jar...............

Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/ec2-user/pacbot/installer/awsterraformbuild.py", line 28, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/home/ec2-user/pacbot/installer/jsonRead.py", line 760, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 37, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code()
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 84, in build_jar_and_ui_from_code
    self.copy_jars_to_upload_dir(self.codebase_root_dir)
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 109, in copy_jars_to_upload_dir
    shutil.copy2(copy_file_from, self.upload_dir)
  File "/usr/lib64/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/ec2-user/pacbot/dist/api/pacman-api-admin.jar'
```

**Comment by johnakash** [comment]
Could you please check if the machine from where you tried to install PacBot has at-least 8GB of memory?

**Comment by chrisswanda** [comment]
It did.  I was running t2.xlarge.

**Comment by johnakash** [comment]
Can you share the installation logs (/var/log/pacbot/pacbot-installation.log)?

**Comment by chrisswanda** [comment]
Re-ran everything this morning on a fresh EC2 instance using an Amazon AMI.  I am getting the same error:

`Started building the jar...............

Traceback (most recent call last):
  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/ec2-user/pacbot/installer/awsterraformbuild.py", line 28, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/home/ec2-user/pacbot/installer/jsonRead.py", line 760, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 37, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code()
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 84, in build_jar_and_ui_from_code
    self.copy_jars_to_upload_dir(self.codebase_root_dir)
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 109, in copy_jars_to_upload_dir
    shutil.copy2(copy_file_from, self.upload_dir)
  File "/usr/lib64/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/ec2-user/pacbot/dist/api/pacman-api-admin.jar'`

Looking at the install logs, the last few lines don't really show anything:

`Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

pacbot = arn:aws:lambda:us-east-1:123456789:function:pacbot-submitBatchjob`

Searching backwards through the logs looking for **pacman-api-admin.jar** here is a match:

`aws_ecs_task_definition.admin: Creating...
  arn:                                 "" => "<computed>"
  container_definitions:               "" => "[{\"command\":[\"./entrypoint.sh\"],\"entrypoint\":[\"sh\",\"-c\"],\"environment\":[{\"name\":\"JAR_FILE\",\"value\":\"pacman-api-admin.jar\"},{\"name\":\"CONFIG_PASSWORD\",\"value\":\"pacman\"},{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://internal-pacbot-912521323.us-east-1.elb.amazonaws.com/api/config\"},{\"name\":\"ES_CLUSTER_NAME\",\"value\":\"pacbot-esdomain\"},{\"name\":\"ES_HEIMDALL_HOST_NAME\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"ES_HEIMDALL_PORT\",\"value\":\"80\"},{\"name\":\"ES_HOST_NAME\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"ES_PORT\",\"value\":\"80\"},{\"name\":\"LOGGING_ES_HOST_NAME\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"LOGGING_ES_PORT\",\"value\":\"80\"},{\"name\":\"PACMAN_HOST_NAME\",\"value\":\"http://internal-pacbot-912521323.us-east-1.elb.amazonaws.com\"},{\"name\":\"RDS_PASSWORD\",\"value\":\"pacbot123\"},{\"name\":\"RDS_URL\",\"value\":\"jdbc:mysql://pacbotdbinstance.c9c29krzsy4z.us-east-1.rds.amazonaws.com/pacmandata\"},{\"name\":\"RDS_USERNAME\",\"value\":\"pacbotuser\"},{\"name\":\"ES_UPDATE_HOST\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"ES_UPDATE_PORT\",\"value\":\"80\"},{\"name\":\"ES_UPDATE_CLUSTER_NAME\",\"value\":\"pacbot-esdomain\"},{\"name\":\"SECURITY_USERNAME\",\"value\":\"admin\"},{\"name\":\"SECURITY_PASSWORD\",\"value\":\"admin@123\"},{\"name\":\"ACCESS_KEY\",\"value\":\"test_key_1\"},{\"name\":\"SECRET_KEY\",\"value\":\"test_key_2\"},{\"name\":\"DOMAIN_URL\",\"value\":\"http://internal-pacbot-912521323.us-east-1.elb.amazonaws.com/api/admin\"},{\"name\":\"ADMIN_SERVER\",\"value\":\"http://localhost/pacmonitor\"},{\"name\":\"ROLE_ARN\",\"value\":\"arn:aws:iam::123456789:role/pacbot_ecs_role\"},{\"name\":\"JOB_FUNCTION_NAME\",\"value\":\"pacbot-submitBatchjob\"},{\"name\":\"JOB_FUNCTION_ARN\",\"value\":\"arn:aws:lambda:us-east-1:123456789:function:pacbot-submitBatchjob\"},{\"name\":\"RULE_FUNCTION_NAME\",\"value\":\"pacbot-SubmitRuleExecutionJob\"},{\"name\":\"RULE_FUNCTION_ARN\",\"value\":\"arn:aws:lambda:us-east-1:1234567897:function:pacbot-SubmitRuleExecutionJob\"}],\"essential\":true,\"image\":\"123456789.dkr.ecr.us-east-1.amazonaws.com/pacbot-api:latest\",\"logConfiguration\":{\"logDriver\":\"awslogs\",\"options\":{\"awslogs-group\":\"pacbot_oss_apis\",\"awslogs-region\":\"us-east-1\",\"awslogs-stream-prefix\":\"admin\"}},\"memory\":1024,\"name\":\"admin\",\"networkMode\":\"awsvpc\",\"portMappings\":[{\"containerPort\":80,\"hostPort\":80}]}]"`

**Comment by chrisswanda** [comment]
Searching backwards through the logs looking for **pacman-api-admin.jar** here is a match:

```
`aws_ecs_task_definition.admin: Creating...
  arn:                                 "" => "<computed>"
  container_definitions:               "" => "[{\"command\":[\"./entrypoint.sh\"],\"entrypoint\":[\"sh\",\"-c\"],\"environment\":[{\"name\":\"JAR_FILE\",\"value\":\"pacman-api-admin.jar\"},{\"name\":\"CONFIG_PASSWORD\",\"value\":\"pacman\"},{\"name\":\"CONFIG_SERVER_URL\",\"value\":\"http://internal-pacbot-912521323.us-east-1.elb.amazonaws.com/api/config\"},{\"name\":\"ES_CLUSTER_NAME\",\"value\":\"pacbot-esdomain\"},{\"name\":\"ES_HEIMDALL_HOST_NAME\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"ES_HEIMDALL_PORT\",\"value\":\"80\"},{\"name\":\"ES_HOST_NAME\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"ES_PORT\",\"value\":\"80\"},{\"name\":\"LOGGING_ES_HOST_NAME\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"LOGGING_ES_PORT\",\"value\":\"80\"},{\"name\":\"PACMAN_HOST_NAME\",\"value\":\"http://internal-pacbot-912521323.us-east-1.elb.amazonaws.com\"},{\"name\":\"RDS_PASSWORD\",\"value\":\"pacbot123\"},{\"name\":\"RDS_URL\",\"value\":\"jdbc:mysql://pacbotdbinstance.c9c29krzsy4z.us-east-1.rds.amazonaws.com/pacmandata\"},{\"name\":\"RDS_USERNAME\",\"value\":\"pacbotuser\"},{\"name\":\"ES_UPDATE_HOST\",\"value\":\"vpc-pacbot-esdomain-xow2hqfsxjgnz4gv7pz447qaum.us-east-1.es.amazonaws.com\"},{\"name\":\"ES_UPDATE_PORT\",\"value\":\"80\"},{\"name\":\"ES_UPDATE_CLUSTER_NAME\",\"value\":\"pacbot-esdomain\"},{\"name\":\"SECURITY_USERNAME\",\"value\":\"admin\"},{\"name\":\"SECURITY_PASSWORD\",\"value\":\"admin@123\"},{\"name\":\"ACCESS_KEY\",\"value\":\"test_key_1\"},{\"name\":\"SECRET_KEY\",\"value\":\"test_key_2\"},{\"name\":\"DOMAIN_URL\",\"value\":\"http://internal-pacbot-912521323.us-east-1.elb.amazonaws.com/api/admin\"},{\"name\":\"ADMIN_SERVER\",\"value\":\"http://localhost/pacmonitor\"},{\"name\":\"ROLE_ARN\",\"value\":\"arn:aws:iam::123456789:role/pacbot_ecs_role\"},{\"name\":\"JOB_FUNCTION_NAME\",\"value\":\"pacbot-submitBatchjob\"},{\"name\":\"JOB_FUNCTION_ARN\",\"value\":\"arn:aws:lambda:us-east-1:123456789:function:pacbot-submitBatchjob\"},{\"name\":\"RULE_FUNCTION_NAME\",\"value\":\"pacbot-SubmitRuleExecutionJob\"},{\"name\":\"RULE_FUNCTION_ARN\",\"value\":\"arn:aws:lambda:us-east-1:1234567897:function:pacbot-SubmitRuleExecutionJob\"}],\"essential\":true,\"image\":\"123456789.dkr.ecr.us-east-1.amazonaws.com/pacbot-api:latest\",\"logConfiguration\":{\"logDriver\":\"awslogs\",\"options\":{\"awslogs-group\":\"pacbot_oss_apis\",\"awslogs-region\":\"us-east-1\",\"awslogs-stream-prefix\":\"admin\"}},\"memory\":1024,\"name\":\"admin\",\"networkMode\":\"awsvpc\",\"portMappings\":[{\"containerPort\":80,\"hostPort\":80}]}]"````

**Comment by johnakash** [comment]
@chrisswanda , can we have a quick screen share and troubleshoot?

**Comment by chrisswanda** [comment]
I have already torn down the infrastructure.  We have been evaluating various compliance and monitoring tools; and I was waiting to test out Pacbot to see if it would fit our needs.  

Due to timelines and schedules, it would be sometime next week before I could even attempt to evaluate or test this out again.  If you'd like to try again next week that is great, or otherwise, I'll continue to monitor the project and mess around with it when I have free time.

**Comment by niteshsaiini** [comment]
i have the same error while installing pacbot

**Comment by evets007** [comment]
@johnakash Facing the same issue.
Running on Amazon linux AMI - t2.large

Traceback (most recent call last):

  File "setup_pacman.py", line 213, in <module>
    _access_validation(assignedpolicieslist, user_name, user_arn)
  File "setup_pacman.py", line 190, in _access_validation
    awsterraformbuild._create_aws_resources(accessKey, secretKey, region)
  File "/home/ec2-user/pacbot/installer/awsterraformbuild.py", line 28, in _create_aws_resources
    jsonRead._build_ui_apps(aws_access_key, aws_secret_key, region)
  File "/home/ec2-user/pacbot/installer/jsonRead.py", line 760, in _build_ui_apps
    bucket=_get_s3_bucket_name() + '-' + _get_base_accountid()
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 37, in build_api_and_ui_apps
    self.build_jar_and_ui_from_code()
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 84, in build_jar_and_ui_from_code
    self.copy_jars_to_upload_dir(self.codebase_root_dir)
  File "/home/ec2-user/pacbot/installer/ui/build_apps.py", line 109, in copy_jars_to_upload_dir
    shutil.copy2(copy_file_from, self.upload_dir)
  File "/usr/lib64/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/ec2-user/pacbot/dist/api/pacman-api-admin.jar'

**Comment by johnakash** [comment]
@niteshsaiini / @evets007 , Could you please join to out Gitter and have a quick discussion?

**Comment by evets007** [comment]
@johnakash Sure.

**Comment by evets007** [comment]
This issue got resolved when I cloned the contents of the project in the /opt folder instead of the /home/ec2-user as suggested by @johnakash  and I used CentOS instead of an Amazon AMI.
